### ISSUE TITLE
Mermiad docker image not friendly to use/doesn't work

### ISSUE THREAD

**Issue by joshcarp** [joshcarp/syslcatalog#201]
Trying to run the docker image with mermaid:
Attempt 1:
- Needed to set a plantuml var even though I was using mermiad
```
docker run --rm -p 6900:6900 -v $(pwd):/usr/:ro anzbank/sysl-catalog:mermaid-v1.4.181 --mermaid input.sysl --serve

time="2020-08-18T01:54:51Z" level=fatal msg="Error: Set SYSL_PLANTUML env variable or --plantuml flag"

```

Attempt 2:
- Set a plantuml dummy var
- `panic: exec: "google-chrome": executable file not found in $PATH`
```
docker run --rm -p 6900:6900 -v $(pwd):/usr/:ro anzbank/sysl-catalog:mermaid-v1.4.181 --mermaid --plantuml="asdjk" input.sysl --serve

Serving on http://localhost:6900
0 / 6 [_____________________________________________________________________________] 0.00% ? p/s 0sThe generated files are output to folder `/`
panic: exec: "google-chrome": executable file not found in $PATH

goroutine 5 [running]:
github.com/anz-bank/mermaid-go/mermaid.Init(0xbfc6eb20c0b87db0)
        /go/pkg/mod/github.com/anz-bank/mermaid-go@v0.1.1/mermaid/mermaid.go:38 +0x11d
github.com/anz-bank/sysl-catalog/pkg/catalog.MakeMermaidGenerator(...)
        /src/pkg/catalog/util.go:328
github.com/anz-bank/sysl-catalog/pkg/catalog.(*Generator).Run(0xc000782300)
        /src/pkg/catalog/generator.go:268 +0x337
github.com/anz-bank/sysl-catalog/pkg/catalog.(*Generator).Update(0xc000782300, 0xc000044200, 0xc000471e28, 0x1, 0x1, 0x0)
        /src/pkg/catalog/server.go:37 +0x173
main.main.func1(0x1253ca0, 0xc000044180)
        /src/main.go:93 +0x1ad
github.com/anz-bank/sysl-catalog/pkg/watcher.WatchFile.func1(0xc00038e100, 0xc000401860)
        /src/pkg/watcher/watcher.go:18 +0x245
created by github.com/anz-bank/sysl-catalog/pkg/watcher.WatchFile
        /src/pkg/watcher/watcher.go:14 +0xa9
```

**Comment by cuminandpaprika** [comment]
Can you please try with

```
docker run --rm -p 6900:6900 -e SYSL_MODULES=github -v $(pwd):/usr/sysl:rw anzbank/sysl-catalog:mermaid-v1.4.185 --mermaid sysl/input.sysl -o test
```

If it works, I'll need to fix up the docs
